name: ChannelFinWatcher-Dev

services:
  db-init:
    image: alpine:latest
    volumes:
      - ./test/data:/data
      - ./test/media:/media
      - ./test/temp:/temp
    command: >
      sh -c "
        mkdir -p /data /media /temp &&
        chmod 755 /data /media /temp &&
        echo 'Local directories initialized for development'
      "

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: channelfinwatcher-backend-dev
    restart: always
    ports:
      - "8001:8000"
    volumes:
      # Mount local code for live updates
      - ./backend:/app
      # Keep data/media/temp in local storage (no Nextcloud sync)
      - ./test/data:/app/data
      - ./test/media:/app/media
      - ./test/temp:/app/temp
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:////app/data/app.db
      - MEDIA_DIR=/app/media
      - TEMP_DIR=/app/temp
      - CONFIG_FILE=/app/data/config.yaml
      - COOKIES_FILE=/app/data/cookies.txt
      - TZ=America/Chicago
    depends_on:
      - db-init
    networks:
      - channelfinwatcher-net

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: channelfinwatcher-frontend-dev
    restart: always
    ports:
      - "3333:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - channelfinwatcher-net

networks:
  channelfinwatcher-net:
    name: channelfinwatcher-net
