version: '3.8'

services:
  channelfinwatcher:
    image: ghcr.io/miguelarios/channelfinwatcher:latest
    container_name: channelfinwatcher
    restart: unless-stopped
    ports:
      - "3000:3000"  # Frontend (Web UI)
      - "8000:8000"  # Backend API (optional, for direct API access)
    volumes:
      # Data directory: databases, config, cookies
      - ./data:/app/data

      # Media directory: downloaded videos
      - ./media:/app/media

      # Temp directory: download staging (can use fast cache drive)
      - ./temp:/app/temp
    environment:
      # Timezone for scheduler (set to your local timezone)
      - TZ=America/Chicago

      # User/Group ID for file permissions (match your host user)
      # Find your UID/GID: run 'id' command on Linux/Mac
      - PUID=1000  # Default: 1000 (change to match your user)
      - PGID=1000  # Default: 1000 (change to match your group)

      # Optional: Customize paths (defaults shown)
      # - DATABASE_URL=sqlite:///data/app.db
      # - MEDIA_DIR=/app/media
      # - TEMP_DIR=/app/temp
      # - CONFIG_FILE=/app/data/config.yaml
      # - COOKIES_FILE=/app/data/cookies.txt
    networks:
      - channelfinwatcher-net
    healthcheck:
      test: ["CMD", "curl", "-f", "http://localhost:3000", "&&", "curl", "-f", "http://localhost:8000/health"]
      interval: 30s
      timeout: 10s
      retries: 3
      start_period: 60s

networks:
  channelfinwatcher-net:
    driver: bridge
