services:
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    ports:
      - "8000:8000"
    volumes:
      - ./backend:/app
      # Local directory mounts for development
      - ./data:/app/data
      - ./config:/app/config
      - ./media:/app/media
      - ./temp:/app/temp
    environment:
      - PYTHONPATH=/app
      - DATABASE_URL=sqlite:///data/app.db
      - MEDIA_DIR=/app/media
      - TEMP_DIR=/app/temp
      - CONFIG_FILE=/app/config/config.yaml
      - TZ=America/Chicago  # CDT/CST timezone for scheduler
    depends_on:
      - db-init
    networks:
      - app-network

  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    ports:
      - "3000:3000"
    volumes:
      - ./frontend:/app
      - /app/node_modules
    environment:
      - NEXT_PUBLIC_API_URL=http://backend:8000
    depends_on:
      - backend
    networks:
      - app-network

  db-init:
    image: alpine:latest
    volumes:
      - ./data:/data
      - ./config:/config
      - ./media:/media
      - ./temp:/temp
    command: >
      sh -c "
        mkdir -p /data /config /media /temp &&
        chmod 755 /data /config /media /temp &&
        echo 'Local directories initialized for development' &&
        echo 'You can now watch files in ./data ./config ./media ./temp'
      "

volumes:
  # Only node_modules needs to be a docker volume for performance
  node_modules:

networks:
  app-network:
    driver: bridge