"""add completed_at to download_history

Revision ID: 35ea57b969d7
Revises: c3d8f2e5a9b4
Create Date: 2025-08-20 03:33:24.105535

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '35ea57b969d7'
down_revision: Union[str, None] = 'c3d8f2e5a9b4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('download_history', sa.Column('completed_at', sa.DateTime(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('download_history', 'completed_at')
    # ### end Alembic commands ###