"""add file_exists column to downloads table

Revision ID: 61c8248141c7
Revises: 426bc5cca72e
Create Date: 2025-08-30 16:51:19.833035

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '61c8248141c7'
down_revision: Union[str, None] = '426bc5cca72e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_downloads_channel_status', table_name='downloads')
    op.drop_index('ix_downloads_video_id', table_name='downloads')
    op.create_index(op.f('ix_downloads_video_id'), 'downloads', ['video_id'], unique=True)
    op.create_index('idx_download_channel_status', 'downloads', ['channel_id', 'status'], unique=False)
    op.create_index('idx_download_upload_date', 'downloads', ['upload_date'], unique=False)
    op.create_index('idx_download_video_id', 'downloads', ['video_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index('idx_download_video_id', table_name='downloads')
    op.drop_index('idx_download_upload_date', table_name='downloads')
    op.drop_index('idx_download_channel_status', table_name='downloads')
    op.drop_index(op.f('ix_downloads_video_id'), table_name='downloads')
    op.create_index('ix_downloads_video_id', 'downloads', ['video_id'], unique=False)
    op.create_index('idx_downloads_channel_status', 'downloads', ['channel_id', 'status'], unique=False)
    # ### end Alembic commands ###