"""Initial database schema

Revision ID: a5dc5e4ba46b
Revises: 
Create Date: 2025-07-29 04:34:25.343649

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a5dc5e4ba46b'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('application_settings',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('key', sa.String(), nullable=False),
    sa.Column('value', sa.Text(), nullable=True),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_settings_key', 'application_settings', ['key'], unique=False)
    op.create_index(op.f('ix_application_settings_id'), 'application_settings', ['id'], unique=False)
    op.create_index(op.f('ix_application_settings_key'), 'application_settings', ['key'], unique=True)
    op.create_table('channels',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('url', sa.String(), nullable=False),
    sa.Column('channel_id', sa.String(), nullable=True),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('limit', sa.Integer(), nullable=True),
    sa.Column('enabled', sa.Boolean(), nullable=True),
    sa.Column('schedule_override', sa.String(), nullable=True),
    sa.Column('quality_preset', sa.String(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('updated_at', sa.DateTime(), nullable=True),
    sa.Column('last_check', sa.DateTime(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_channel_enabled_lastcheck', 'channels', ['enabled', 'last_check'], unique=False)
    op.create_index(op.f('ix_channels_channel_id'), 'channels', ['channel_id'], unique=True)
    op.create_index(op.f('ix_channels_enabled'), 'channels', ['enabled'], unique=False)
    op.create_index(op.f('ix_channels_id'), 'channels', ['id'], unique=False)
    op.create_index(op.f('ix_channels_url'), 'channels', ['url'], unique=True)
    op.create_table('download_history',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('run_date', sa.DateTime(), nullable=True),
    sa.Column('videos_found', sa.Integer(), nullable=True),
    sa.Column('videos_downloaded', sa.Integer(), nullable=True),
    sa.Column('videos_skipped', sa.Integer(), nullable=True),
    sa.Column('videos_failed', sa.Integer(), nullable=True),
    sa.Column('duration_seconds', sa.Integer(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_history_channel_date', 'download_history', ['channel_id', 'run_date'], unique=False)
    op.create_index(op.f('ix_download_history_channel_id'), 'download_history', ['channel_id'], unique=False)
    op.create_index(op.f('ix_download_history_id'), 'download_history', ['id'], unique=False)
    op.create_index(op.f('ix_download_history_run_date'), 'download_history', ['run_date'], unique=False)
    op.create_table('downloads',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('channel_id', sa.Integer(), nullable=False),
    sa.Column('video_id', sa.String(), nullable=False),
    sa.Column('title', sa.String(), nullable=False),
    sa.Column('upload_date', sa.String(), nullable=False),
    sa.Column('duration', sa.String(), nullable=True),
    sa.Column('file_path', sa.String(), nullable=True),
    sa.Column('file_size', sa.Integer(), nullable=True),
    sa.Column('status', sa.String(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.Column('completed_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['channel_id'], ['channels.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index('idx_download_channel_status', 'downloads', ['channel_id', 'status'], unique=False)
    op.create_index('idx_download_upload_date', 'downloads', ['upload_date'], unique=False)
    op.create_index('idx_download_video_id', 'downloads', ['video_id'], unique=False)
    op.create_index(op.f('ix_downloads_channel_id'), 'downloads', ['channel_id'], unique=False)
    op.create_index(op.f('ix_downloads_id'), 'downloads', ['id'], unique=False)
    op.create_index(op.f('ix_downloads_status'), 'downloads', ['status'], unique=False)
    op.create_index(op.f('ix_downloads_video_id'), 'downloads', ['video_id'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_downloads_video_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_status'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_id'), table_name='downloads')
    op.drop_index(op.f('ix_downloads_channel_id'), table_name='downloads')
    op.drop_index('idx_download_video_id', table_name='downloads')
    op.drop_index('idx_download_upload_date', table_name='downloads')
    op.drop_index('idx_download_channel_status', table_name='downloads')
    op.drop_table('downloads')
    op.drop_index(op.f('ix_download_history_run_date'), table_name='download_history')
    op.drop_index(op.f('ix_download_history_id'), table_name='download_history')
    op.drop_index(op.f('ix_download_history_channel_id'), table_name='download_history')
    op.drop_index('idx_history_channel_date', table_name='download_history')
    op.drop_table('download_history')
    op.drop_index(op.f('ix_channels_url'), table_name='channels')
    op.drop_index(op.f('ix_channels_id'), table_name='channels')
    op.drop_index(op.f('ix_channels_enabled'), table_name='channels')
    op.drop_index(op.f('ix_channels_channel_id'), table_name='channels')
    op.drop_index('idx_channel_enabled_lastcheck', table_name='channels')
    op.drop_table('channels')
    op.drop_index(op.f('ix_application_settings_key'), table_name='application_settings')
    op.drop_index(op.f('ix_application_settings_id'), table_name='application_settings')
    op.drop_index('idx_settings_key', table_name='application_settings')
    op.drop_table('application_settings')
    # ### end Alembic commands ###